### ISSUE TITLE
The website's content disappears after it has been loaded.

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [rwieruch/purchasing-power-parity#12]
Hi 👋🏼,

When I visited the PPP website, the content fades away after a very short time. The video below illustrates what I encountered.

Kindly take a look.
![ppp isue](https://user-images.githubusercontent.com/48127194/134291637-2f098182-7ac0-4ed9-8a48-5b563e5ed26a.gif)

**Comment by rwieruch** [comment]
https://github.com/rwieruch/purchasing-power-parity/issues/13
