### ISSUE TITLE
API SSL certificate issue

### ISSUE THREAD

**Issue by ShaunDychko** [rwieruch/purchasing-power-parity#13]
Visiting https://api.purchasing-power-parity.com/?target=ID results in the message
```
{
  "message": "Hostname/IP does not match certificate's altnames: Host: restcountries.eu. is not in the cert's altnames: DNS:shortener.secureserver.net, DNS:www.shortener.secureserver.net"
}
```

**Comment by strzibny** [comment]
I came across the same... it's a silent error, since your PPP just stops working. @rwieruch are you looking into it? I wonder if we can self host the API part or if there is some alternative. Can we help somehow?

**Comment by rwieruch** [comment]
The underlying API `restcountries.eu` changed to `countrylayer.com`. And with it their entire API. I am in contact with their support, because they do no return all the data that they are advertising, but it's super slow on their end ... Sorry for the issue!

**Comment by juanwmedia** [comment]
> The underlying API `restcountries.eu` changed to `countrylayer.com`. And with it their entire API. I am in contact with their support, because they do no return all the data that they are advertising, but it's super slow on their end ... Sorry for the issue!

Hey @rwieruch any news on this?. Thanks!

**Comment by rwieruch** [comment]
Should be up and running again.

**Comment by strzibny** [comment]
Can confirm. Perfect!

**Comment by juanwmedia** [comment]
Confirmed. Thanks.
