### ISSUE TITLE
How does the API calculates PPP?

### ISSUE THREAD

**Issue by SapneshNaik** [rwieruch/purchasing-power-parity#7]
Hi, awesome package and great work!

I want to use your API in a project that might last a long time (an open-source project). I want to know how to calculate PPP so that I can integrate it into my own set-up so it does not have a reliance on your API. However, I would be happy to host a mirror for your API as well if you are interested in sharing the source code of it.

Let me know,

Thanks,
Sapnesh

**Comment by rwieruch** [comment]
Hi Sapnesh,

all the implementation details can be found here https://github.com/rwieruch/purchasing-power-parity <https://github.com/rwieruch/purchasing-power-parity> It’s possible to install the API as JS library, but then you would have to provide your own API keys for the third-party APIs. If you implement yourself, you would need the data from somewhere else to calculate the PPP as well. The API that I have set up calculates the PPP once a day.

Best wishes,
Robin
